roles:
    root: 
        - admin
        - supervisor
        - guest
    admin: 
        - supervisor
        - guest
    supervisor: 
        - guest
    guest: 

useGoogleAuth: true

# Note that you MUST have either security question or 
# gmail sent to true
security_question:
    true
gmail:
    false